POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de phyton"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/8b6da91a-688c-49bf-94da-54c0ce9b5853


###

DELETE http://localhost:3333/courses/8b6da91a-688c-49bf-94da-54c0ce9b5853
