POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": ""
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/7c91f99a-e479-4667-9f67-00a0ac7fa27f
